"""Initial migration

Revision ID: 54f88ce118a5
Revises: 
Create Date: 2025-10-27 19:37:56.411993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f88ce118a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('call_event_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_responded', sa.Boolean(), nullable=True),
    sa.Column('conversation_completed', sa.Boolean(), nullable=True),
    sa.Column('booking_created', sa.Boolean(), nullable=True),
    sa.Column('booking_abandoned', sa.Boolean(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('outreach_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversation_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('customer_messages', sa.Integer(), nullable=True),
    sa.Column('bot_messages', sa.Integer(), nullable=True),
    sa.Column('last_flow_state', sa.String(length=50), nullable=True),
    sa.Column('dropped_off', sa.Boolean(), nullable=True),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('conversation_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('time_to_booking_seconds', sa.Integer(), nullable=True),
    sa.Column('estimated_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['call_event_id'], ['call_events.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index('ix_metrics_booking_created', 'conversation_metrics', ['business_id', 'booking_created'], unique=False)
    op.create_index('ix_metrics_business_created', 'conversation_metrics', ['business_id', 'created_at'], unique=False)
    op.create_index('ix_metrics_customer_responded', 'conversation_metrics', ['business_id', 'customer_responded'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metrics_customer_responded', table_name='conversation_metrics')
    op.drop_index('ix_metrics_business_created', table_name='conversation_metrics')
    op.drop_index('ix_metrics_booking_created', table_name='conversation_metrics')
    op.drop_table('conversation_metrics')
    # ### end Alembic commands ###
