"""Add booking_initiated tracking to conversation_metrics

Revision ID: 6fa2ff1f54bb
Revises: 9f1ffc2e0106
Create Date: 2025-12-21 12:54:26.144261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fa2ff1f54bb'
down_revision: Union[str, Sequence[str], None] = '9f1ffc2e0106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add booking_initiated tracking fields to conversation_metrics
    op.add_column('conversation_metrics', sa.Column('booking_initiated', sa.Boolean(), nullable=True))
    op.add_column('conversation_metrics', sa.Column('booking_initiated_at', sa.DateTime(timezone=True), nullable=True))

    # Set default value for existing rows
    op.execute('UPDATE conversation_metrics SET booking_initiated = false WHERE booking_initiated IS NULL')

    # Make booking_initiated non-nullable after setting defaults
    op.alter_column('conversation_metrics', 'booking_initiated',
                    existing_type=sa.Boolean(),
                    nullable=False,
                    server_default=sa.text('false'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove booking_initiated tracking fields
    op.drop_column('conversation_metrics', 'booking_initiated_at')
    op.drop_column('conversation_metrics', 'booking_initiated')

